"""What counts as activity, and how counts reach the database."""

from __future__ import annotations

from unittest.mock import MagicMock

import discord
import pytest

from prunebot.services.activity import ActivityBuffer, counting_channel_id, should_count

from .conftest import GUILD_ID
from .test_sweep_integration import make_config

TEXT_CHANNEL_ID = 500
OTHER_CHANNEL_ID = 501
FORUM_ID = 600


def make_message(
    *,
    channel_id: int = TEXT_CHANNEL_ID,
    bot: bool = False,
    kind: discord.MessageType = discord.MessageType.default,
    thread_of: int | None = None,
    forum: bool = False,
    in_guild: bool = True,
):
    message = MagicMock(spec=discord.Message)
    message.guild = MagicMock(spec=discord.Guild) if in_guild else None
    message.author = MagicMock()
    message.author.bot = bot
    message.type = kind

    if thread_of is not None:
        channel = MagicMock(spec=discord.Thread)
        channel.parent_id = thread_of
        channel.id = 9999
        channel.parent = MagicMock()
        channel.parent.type = (
            discord.ChannelType.forum if forum else discord.ChannelType.text
        )
    else:
        channel = MagicMock(spec=discord.TextChannel)
        channel.id = channel_id
    message.channel = channel
    return message


# ------------------------------------------------------------------- what counts


def test_an_ordinary_message_counts():
    assert should_count(make_message(), make_config()) is True


def test_a_reply_counts():
    assert should_count(make_message(kind=discord.MessageType.reply), make_config()) is True


@pytest.mark.parametrize(
    "kind",
    [
        discord.MessageType.new_member,
        discord.MessageType.premium_guild_subscription,
        discord.MessageType.pins_add,
        discord.MessageType.thread_created,
    ],
)
def test_system_messages_do_not_count(kind):
    """Joining, boosting and pinning are generated by Discord, not by a person."""
    assert should_count(make_message(kind=kind), make_config()) is False


def test_bots_never_count():
    assert should_count(make_message(bot=True), make_config()) is False


def test_dms_do_not_count():
    assert should_count(make_message(in_guild=False), make_config()) is False


# ---------------------------------------------------------------------- channels


def test_excluded_channels_do_not_count():
    config = make_config(activity={"channels": {"mode": "exclude", "exclude": [TEXT_CHANNEL_ID]}})
    assert should_count(make_message(channel_id=TEXT_CHANNEL_ID), config) is False
    assert should_count(make_message(channel_id=OTHER_CHANNEL_ID), config) is True


def test_include_mode_counts_only_the_listed_channels():
    config = make_config(activity={"channels": {"mode": "include", "include": [TEXT_CHANNEL_ID]}})
    assert should_count(make_message(channel_id=TEXT_CHANNEL_ID), config) is True
    assert should_count(make_message(channel_id=OTHER_CHANNEL_ID), config) is False


def test_a_new_channel_counts_automatically_in_exclude_mode():
    """The reason exclude is the default: nobody has to remember to add channels."""
    config = make_config(activity={"channels": {"mode": "exclude", "exclude": [OTHER_CHANNEL_ID]}})
    assert should_count(make_message(channel_id=12345), config) is True


# ----------------------------------------------------------------------- threads


def test_thread_messages_count_by_default():
    assert should_count(make_message(thread_of=TEXT_CHANNEL_ID), make_config()) is True


def test_forum_posts_count_by_default():
    assert (
        should_count(make_message(thread_of=FORUM_ID, forum=True), make_config()) is True
    )


def test_threads_can_be_turned_off():
    config = make_config(activity={"count_threads": False})
    assert should_count(make_message(thread_of=TEXT_CHANNEL_ID), config) is False
    assert should_count(make_message(), config) is True  # plain channels unaffected


def test_forum_posts_can_be_turned_off_independently():
    config = make_config(activity={"count_forum_posts": False})
    assert should_count(make_message(thread_of=FORUM_ID, forum=True), config) is False
    assert should_count(make_message(thread_of=TEXT_CHANNEL_ID), config) is True


def test_a_thread_inherits_its_parents_exclusion():
    """Excluding #bot-spam excludes threads inside it, with no per-thread config."""
    config = make_config(activity={"channels": {"mode": "exclude", "exclude": [TEXT_CHANNEL_ID]}})
    assert should_count(make_message(thread_of=TEXT_CHANNEL_ID), config) is False


def test_counting_channel_id_resolves_threads_to_their_parent():
    assert counting_channel_id(make_message(thread_of=TEXT_CHANNEL_ID)) == TEXT_CHANNEL_ID
    assert counting_channel_id(make_message(channel_id=77)) == 77


# ------------------------------------------------------------------------ buffer


async def test_buffer_accumulates_and_flushes_once(store):
    buffer = ActivityBuffer(store)
    for _ in range(5):
        buffer.record(GUILD_ID, 42, 1_700_000_000)
    assert buffer.pending == 5

    await buffer.flush()
    assert buffer.pending == 0
    assert await store.window_counts(GUILD_ID, 0) == {42: 5}


async def test_flushing_twice_does_not_double_count(store):
    buffer = ActivityBuffer(store)
    buffer.record(GUILD_ID, 42, 1_700_000_000)
    await buffer.flush()
    await buffer.flush()
    assert await store.window_counts(GUILD_ID, 0) == {42: 1}


async def test_messages_on_different_days_land_in_different_buckets(store):
    buffer = ActivityBuffer(store)
    buffer.record(GUILD_ID, 42, 1_700_000_000)
    buffer.record(GUILD_ID, 42, 1_700_000_000 + 86_400)
    await buffer.flush()
    assert len(await store.user_daily(GUILD_ID, 42, 0)) == 2


async def test_flush_records_the_latest_message_time(store):
    buffer = ActivityBuffer(store)
    buffer.record(GUILD_ID, 42, 1_700_000_000)
    buffer.record(GUILD_ID, 42, 1_700_000_500)
    await buffer.flush()
    row = await store.get_member(GUILD_ID, 42)
    assert row.last_message_at == 1_700_000_500


async def test_flushing_an_empty_buffer_is_free(store):
    assert await ActivityBuffer(store).flush() == 0


# --------------------------------------------------------- warning DM rendering


def test_warning_embed_renders_the_configured_template():
    from prunebot.config import MessagesSection
    from prunebot.ui.embeds import message_context, warning_embed

    messages = MessagesSection(
        warn_title="Oi {member}",
        warn_body="No posts in {window_days}d, {mention}. Gone {deadline}.",
    )
    context = message_context(
        guild_name="Test Server",
        member_name="casey",
        member_id=42,
        window_days=30,
        min_messages=1,
        days_left=90,
        kick_after_days=90,
    )
    embed = warning_embed(messages=messages, context=context)
    assert embed.title == "Oi casey"
    assert "No posts in 30d, <@42>." in embed.description
    assert "<t:" in embed.description  # a live Discord countdown, not a fixed string


def test_threshold_placeholder_adapts_to_min_messages():
    from prunebot.ui.embeds import message_context

    def threshold(min_messages):
        return message_context(
            guild_name="g",
            member_name="m",
            member_id=1,
            window_days=30,
            min_messages=min_messages,
            days_left=1,
            kick_after_days=90,
        )["threshold"]

    assert threshold(1) == "posted anything"
    assert threshold(5) == "posted at least 5 messages"


def test_final_and_kick_templates_are_used_for_their_own_messages():
    from prunebot.config import MessagesSection
    from prunebot.ui.embeds import message_context, pre_kick_embed, warning_embed

    messages = MessagesSection(
        warn_title="initial", final_title="final", kick_title="removed from {guild}"
    )
    context = message_context(
        guild_name="Test Server",
        member_name="m",
        member_id=1,
        window_days=30,
        min_messages=1,
        days_left=3,
        kick_after_days=90,
    )
    assert warning_embed(messages=messages, context=context).title == "initial"
    assert warning_embed(messages=messages, context=context, final=True).title == "final"
    assert pre_kick_embed(messages=messages, context=context).title == "removed from Test Server"


# ------------------------------------------------- the backfill must not lie


async def test_backfill_refuses_to_claim_coverage_with_no_readable_channels(store):
    """A scan that read nothing once marked a guild fully backfilled, which
    unlocked the sweep against no data at all."""
    from prunebot.services.backfill import BackfillRunner, NothingScanned

    guild = MagicMock(spec=discord.Guild)
    guild.id = GUILD_ID
    guild.name = "Test"
    guild.me = MagicMock()
    guild.text_channels = []
    guild.forums = []

    runner = BackfillRunner(
        store=store,
        config=make_config(),
        guild=guild,
        before=discord.utils.utcnow(),
    )
    with pytest.raises(NothingScanned):
        await runner.run()

    meta = await store.guild_meta(GUILD_ID)
    assert meta["backfilled_at"] is None  # the gate stays locked


async def test_backfill_refuses_to_run_before_the_cache_is_populated(store):
    """An unpopulated guild.me made every channel look unreadable, which was
    indistinguishable from a genuinely locked-down server."""
    from prunebot.services.backfill import BackfillRunner, NotReady

    guild = MagicMock(spec=discord.Guild)
    guild.id = GUILD_ID
    guild.name = "Test"
    guild.me = None

    runner = BackfillRunner(
        store=store,
        config=make_config(),
        guild=guild,
        before=discord.utils.utcnow(),
    )
    with pytest.raises(NotReady):
        await runner.run()

    meta = await store.guild_meta(GUILD_ID)
    assert meta["backfilled_at"] is None
