"""Live message counting, buffered in memory and flushed periodically.

A busy guild can produce thousands of messages a minute. Writing one row per
message would be wasteful and would make SQLite the bottleneck, so counts are
accumulated in a dict and folded into daily buckets on a timer.

The buffer is volatile by design: losing up to `flush_interval_seconds` of counts
on an unclean kill is acceptable for a 30-day window. `Bot.close()` flushes on a
clean shutdown, which is why docker-compose sets a `stop_grace_period`.
"""

from __future__ import annotations

import logging
from collections import defaultdict

import discord

from ..config import Config
from ..db.store import Store
from ..domain.windows import day_of

log = logging.getLogger(__name__)

#: Message types that represent a person actually saying something. Joins, boosts
#: and pin notices are generated by Discord and must not count as participation.
COUNTED_TYPES = frozenset(
    {discord.MessageType.default, discord.MessageType.reply}
)


def counting_channel_id(message: discord.Message) -> int | None:
    """The channel id to test against the include/exclude lists.

    Thread and forum-post messages resolve to their parent channel, so operators
    configure channels once rather than chasing every thread that gets created.
    """
    channel = message.channel
    if isinstance(channel, discord.Thread):
        return channel.parent_id
    return getattr(channel, "id", None)


def should_count(message: discord.Message, config: Config) -> bool:
    if message.guild is None or message.author.bot:
        return False
    if message.type not in COUNTED_TYPES:
        return False

    channel = message.channel
    if isinstance(channel, discord.Thread):
        is_forum = getattr(channel.parent, "type", None) == discord.ChannelType.forum
        if is_forum and not config.activity.count_forum_posts:
            return False
        if not is_forum and not config.activity.count_threads:
            return False

    channel_id = counting_channel_id(message)
    if channel_id is None:
        return False

    channels = config.activity.channels
    if channels.mode == "include":
        return channel_id in set(channels.include)
    return channel_id not in set(channels.exclude)


class ActivityBuffer:
    """Accumulates counts between flushes."""

    def __init__(self, store: Store) -> None:
        self.store = store
        self._counts: defaultdict[tuple[int, int, int], int] = defaultdict(int)
        self._last_seen: dict[tuple[int, int], int] = {}

    def record(self, guild_id: int, user_id: int, timestamp: int) -> None:
        self._counts[(guild_id, user_id, day_of(timestamp))] += 1
        key = (guild_id, user_id)
        if timestamp > self._last_seen.get(key, 0):
            self._last_seen[key] = timestamp

    @property
    def pending(self) -> int:
        return sum(self._counts.values())

    async def flush(self) -> int:
        """Write buffered counts. The buffer is swapped out first so that a
        message arriving mid-flush is not lost or double-counted."""
        if not self._counts and not self._last_seen:
            return 0
        counts, self._counts = self._counts, defaultdict(int)
        last_seen, self._last_seen = self._last_seen, {}

        rows = [(g, u, day, n) for (g, u, day), n in counts.items()]
        written = await self.store.bump_activity(rows)
        await self.store.touch_last_message(
            [(g, u, ts) for (g, u), ts in last_seen.items()]
        )
        if written:
            log.debug("flushed %d activity bucket(s)", written)
        return written
